# 과제 10-5장 Linear Regression - 자전거 통행량 예측

시애틀 프리몬트 다리를 지나는 자전거 통행량을 날씨와 계절, 기타 요인에 따라 예측하시오. (p436 참고)

<img src="https://images.seattletimes.com/wp-content/uploads/2020/01/01022020_bike-count_114545.jpg?d=2040x1360" width=400>

Ken Lambert, "Bike ridership hits record highs on 2 Seattle routes", The Seattle Times, Jan. 6, 2020

1. 교재에서 제공하는 FremontBridge.csv 파일과 SeattleWeather.csv 파일을 읽어 pandas 의 DataFrame 을 각각 생성하시오. (https://github.com/jakevdp/bicycle-data)
2. 2020 년 이전 데이터만 선택하시오.
3. 일별 총 자전거 통행량을 계산하고, 그 계산 결과를 'counts' 컬럼에 추가하시오.
4. 월요일~일요일까지 요일을 이진 데이터로 각각 인코딩 하고, 그 결과를 요일을 나타내는 컬럼들(7개)에 추가하시오.
5. 공휴일 여부를 이진 데이터로 인코딩 하고, 그 결과를 'holiday' 컬럼에 추가하시오.
6. 일자별 평균 날씨 (TAVG) 를 계산한 후, 'temp' 컬럼에 추가하시오.
7. 일자별 강수량(PRCP)을 계산한 후, 'rainfall' 컬럼에 추가하시오.
8. 데이터에서 NA 를 제거하시오.
9. LinearRegression 모델을 이용하여 자전거 통행량을 예측하시오.
10. Matplotlib 를 이용하여 예측 결과를 시각화 하시오.

In [14]:
import pandas as pd
fb = pd.read_csv('FremontBridge.csv', index_col= 'Date', parse_dates=True).sort_index()
fb.head()

C:\Users\user\AppData\Local\Temp\ipykernel_2220\2516591662.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  fb = pd.read_csv('FremontBridge.csv', index_col= 'Date', parse_dates=True).sort_index()

,Fremont Bridge Total,Fremont Bridge East Sidewalk,Fremont Bridge West Sidewalk
Date,,,
2012-10-03 00:00:00,13.0,4.0,9.0
2012-10-03 00:00:00,13.0,4.0,9.0
2012-10-03 01:00:00,10.0,4.0,6.0
2012-10-03 01:00:00,10.0,4.0,6.0
2012-10-03 02:00:00,2.0,1.0,1.0

In [ ]:
sw = pd.read_csv('SeattleWeather.csv', index_col= 'Date', parse_dates=True).sort_index()
sw

,STATION,NAME,DATE,AWND,FMTM,PGTM,PRCP,SNOW,SNWD,TAVG,...,WT04,WT05,WT08,WT09,WT13,WT14,WT16,WT17,WT18,WT22
0,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2012-01-01,10.51,NaN,NaN,0.00,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2012-01-02,10.07,NaN,NaN,0.43,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
2,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2012-01-03,5.14,NaN,NaN,0.03,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2012-01-04,10.51,NaN,NaN,0.80,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
4,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2012-01-05,13.65,NaN,NaN,0.05,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3648,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2021-12-27,9.62,NaN,NaN,0.03,0.5,3.1,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3649,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2021-12-28,8.50,NaN,NaN,NaN,1.0,2.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3650,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2021-12-29,8.50,NaN,NaN,0.13,0.9,2.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3651,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2021-12-30,9.62,NaN,NaN,NaN,3.4,3.1,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3652,USW00024233,"SEATTLE TACOMA AIRPORT, WA US",2021-12-31,6.71,NaN,NaN,0.00,0.0,3.9,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
fb = fb[fb['Date'] < '2021-01-01'] 
fb

KeyError: 'Date'